development:
  adapter: async
  channel_prefix: development_shards_of_the_grid

test:
  adapter: async
  channel_prefix: test_shards_of_the_grid

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: production_shards_of_the_grid
