development:
  adapter: async
  channel_prefix: shards_of_the_grid_development

test:
  adapter: async
  channel_prefix: shards_of_the_grid_test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  channel_prefix: shards_of_the_grid_production
