name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Install Bundler
        run: gem install bundler -v '2.4.10'

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Set up Heroku Authentication
        run: |
          echo "machine git.heroku.com" > ~/.netrc
          echo "  login heroku" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          chmod 600 ~/.netrc
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Set GitHub Authentication
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Add Heroku Git Remote
        run: |
          git remote remove heroku || true
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      - name: Clear Old Assets
        run: |
          DATABASE_URL=postgresql://localhost:5432/dummy RAILS_ENV=production RAILS_GROUPS=assets SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} bin/rails assets:clobber
        env:
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

      - name: Precompile Assets
        run: |
          DATABASE_URL=postgresql://localhost:5432/dummy RAILS_ENV=production RAILS_GROUPS=assets SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} bin/rails assets:precompile --trace
        env:
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

      - name: Commit Precompiled Assets
        run: |
          git add public/assets || true
          git diff --cached --quiet || git commit -m "GitHub Action: Precompiled assets for deployment"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Precompiled Assets to GitHub
        run: |
          git push origin main || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Heroku
        run: git push heroku main --force
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Run Database Migrations
        run: heroku run rails db:migrate --app ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}