name: Pull Request Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true   # Caches gems for faster builds

      - name: Install dependencies
        run: bundle install

      - name: Ensure log directory exists
        run: mkdir -p log

      - name: Set up database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:create
          bin/rails db:schema:load
          bin/rails db:migrate

      - name: Run RSpec tests
        env:
          CURRENCY_CONVERSION_API_KEY: ${{ secrets.CURRENCY_CONVERSION_API_KEY }}
        run: bundle exec rspec

      - name: Run Cucumber tests
        env:
          CURRENCY_CONVERSION_API_KEY: ${{ secrets.CURRENCY_CONVERSION_API_KEY }}
        run: bundle exec cucumber